loadI   [ val 27 ], [ ], [ sr1 ]
loadI   [ val 27 ], [ ], [ sr1 ]
load    [ sr1 ], [ ], [ sr2 ]
load    [ sr1 ], [ ], [ sr2 ]
load    [ sr1 ], [ ], [ sr2 ]
store   [ sr2 ], [ ], [ sr4 ]
add     [ sr1 ], [ sr2 ], [ sr3 ]
sub     [ sr3 ], [ sr4 ], [ sr5 ]
mult    [ sr5 ], [ sr6 ], [ sr10 ]
lshift  [ sr0 ], [ sr3 ], [ sr2 ]
rshift  [ sr2 ], [ sr3 ], [ sr2 ]
output  [ val 1024 ], [ ], [ ]
nop     [ ], [ ], [ ]